# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{tickets}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ivo Dancet"]
  s.date = %q{2009-09-17}
  s.default_executable = %q{tickets}
  s.description = %q{This gem queries lighthouse to get you lists of tickets which are important to you and show them through growl. You can set the queries yourself.}
  s.email = %q{ivo.dancet@by2.be}
  s.executables = ["tickets"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/tickets",
     "config/schedule.rb",
     "lib/tickets.rb",
     "lib/tickets/cli.rb",
     "lib/tickets/core.rb",
     "lib/tickets/tickets_config_example.yaml",
     "spec/spec_helper.rb",
     "spec/tickets_spec.rb"
  ]
  s.has_rdoc = true
  s.homepage = %q{http://github.com/caifara/tickets}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.1}
  s.summary = %q{Stay up to date with urgent or important Lighthouse tickets}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/tickets_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 2

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<>, [">= 0"])
    else
      s.add_dependency(%q<>, [">= 0"])
    end
  else
    s.add_dependency(%q<>, [">= 0"])
  end
end
